# Generated by Django 5.2.6 on 2026-04-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.TextField(help_text='Comma-separated list of ingredients from the user')),
                ('cuisine', models.CharField(help_text='Cuisine preference, e.g. Italian, Indian', max_length=100)),
                ('recipe_body', models.TextField(blank=True, default='', help_text='Markdown recipe from the Sous-Chef agent')),
                ('nutrition_summary', models.TextField(blank=True, default='', help_text='Nutritional analysis from the Nutritionist agent')),
                ('audio_blob_path', models.CharField(blank=True, default='', help_text='Path to audio file from the Narrator agent', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
